spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 40f8a76448148904221e
            clientSecret: db2de4ffb5ea7292ed91062d028d6406baf12d08

server:
  port: 999